import 'package:flutter/material.dart';

class MoodCategory {
  final String name;
  final IconData icon;
  final Color color;
  final String label;
  final String description;
  final double energy;
  final double valence;
  final double danceability;
  final double tempo;

  const MoodCategory({
    required this.name,
    required this.icon,
    required this.color,
    required this.label,
    required this.description,
    required this.energy,
    required this.valence,
    required this.danceability,
    required this.tempo,
  });
}

class MoodCategories {
  static const List<MoodCategory> all = [
    // === ЭНЕРГИЯ И АКТИВНОСТЬ ===
    MoodCategory(
      name: 'energetic',
      icon: Icons.flash_on,
      color: Colors.orange,
      label: 'Энергия',
      description: 'Высокая энергия для активности',
      energy: 0.9,
      valence: 0.7,
      danceability: 0.8,
      tempo: 140,
    ),
    MoodCategory(
      name: 'workout',
      icon: Icons.fitness_center,
      color: Colors.red,
      label: 'Тренировка',
      description: 'Интенсивная музыка для спорта',
      energy: 0.95,
      valence: 0.75,
      danceability: 0.85,
      tempo: 150,
    ),
    MoodCategory(
      name: 'running',
      icon: Icons.directions_run,
      color: Color(0xFFFF5722),
      label: 'Бег',
      description: 'Ритмичная музыка для бега',
      energy: 0.9,
      valence: 0.7,
      danceability: 0.75,
      tempo: 160,
    ),
    MoodCategory(
      name: 'power',
      icon: Icons.bolt,
      color: Color(0xFFFF6F00),
      label: 'Мощь',
      description: 'Мощная энергичная музыка',
      energy: 0.98,
      valence: 0.6,
      danceability: 0.7,
      tempo: 145,
    ),
    MoodCategory(
      name: 'adrenaline',
      icon: Icons.flash_auto,
      color: Color(0xFFD32F2F),
      label: 'Адреналин',
      description: 'Экстремальная музыка',
      energy: 1.0,
      valence: 0.65,
      danceability: 0.8,
      tempo: 170,
    ),

    // === РАССЛАБЛЕНИЕ И СПОКОЙСТВИЕ ===
    MoodCategory(
      name: 'chill',
      icon: Icons.spa,
      color: Colors.blue,
      label: 'Расслабление',
      description: 'Спокойная музыка для релакса',
      energy: 0.3,
      valence: 0.6,
      danceability: 0.4,
      tempo: 85,
    ),
    MoodCategory(
      name: 'sleep',
      icon: Icons.bedtime,
      color: Colors.indigo,
      label: 'Сон',
      description: 'Умиротворяющая музыка для сна',
      energy: 0.15,
      valence: 0.4,
      danceability: 0.2,
      tempo: 60,
    ),
    MoodCategory(
      name: 'meditation',
      icon: Icons.self_improvement,
      color: Color(0xFF7E57C2),
      label: 'Медитация',
      description: 'Музыка для медитации',
      energy: 0.2,
      valence: 0.5,
      danceability: 0.15,
      tempo: 55,
    ),
    MoodCategory(
      name: 'ambient',
      icon: Icons.cloud,
      color: Color(0xFF5C6BC0),
      label: 'Эмбиент',
      description: 'Атмосферная фоновая музыка',
      energy: 0.25,
      valence: 0.5,
      danceability: 0.2,
      tempo: 70,
    ),
    MoodCategory(
      name: 'peaceful',
      icon: Icons.spa_outlined,
      color: Color(0xFF26A69A),
      label: 'Покой',
      description: 'Мирная спокойная музыка',
      energy: 0.2,
      valence: 0.6,
      danceability: 0.25,
      tempo: 65,
    ),

    // === ЭМОЦИИ И НАСТРОЕНИЕ ===
    MoodCategory(
      name: 'happy',
      icon: Icons.sentiment_satisfied,
      color: Colors.yellow,
      label: 'Счастье',
      description: 'Позитивная радостная музыка',
      energy: 0.7,
      valence: 0.9,
      danceability: 0.75,
      tempo: 120,
    ),
    MoodCategory(
      name: 'uplifting',
      icon: Icons.trending_up,
      color: Color(0xFFFFA726),
      label: 'Воодушевление',
      description: 'Вдохновляющая музыка',
      energy: 0.75,
      valence: 0.85,
      danceability: 0.7,
      tempo: 125,
    ),
    MoodCategory(
      name: 'euphoric',
      icon: Icons.celebration_outlined,
      color: Color(0xFFFFEB3B),
      label: 'Эйфория',
      description: 'Эйфорическая музыка',
      energy: 0.85,
      valence: 0.95,
      danceability: 0.85,
      tempo: 130,
    ),
    MoodCategory(
      name: 'melancholic',
      icon: Icons.sentiment_dissatisfied,
      color: Color(0xFF546E7A),
      label: 'Меланхолия',
      description: 'Грустная задумчивая музыка',
      energy: 0.3,
      valence: 0.25,
      danceability: 0.3,
      tempo: 75,
    ),
    MoodCategory(
      name: 'nostalgic',
      icon: Icons.history,
      color: Color(0xFF8D6E63),
      label: 'Ностальгия',
      description: 'Ностальгическая музыка',
      energy: 0.4,
      valence: 0.4,
      danceability: 0.4,
      tempo: 90,
    ),

    // === СОЦИАЛЬНЫЕ АКТИВНОСТИ ===
    MoodCategory(
      name: 'party',
      icon: Icons.celebration,
      color: Colors.pink,
      label: 'Вечеринка',
      description: 'Музыка для вечеринок',
      energy: 0.9,
      valence: 0.85,
      danceability: 0.95,
      tempo: 128,
    ),
    MoodCategory(
      name: 'dance',
      icon: Icons.music_note,
      color: Color(0xFFEC407A),
      label: 'Танцы',
      description: 'Танцевальная музыка',
      energy: 0.85,
      valence: 0.8,
      danceability: 0.95,
      tempo: 125,
    ),
    MoodCategory(
      name: 'club',
      icon: Icons.nightlife,
      color: Color(0xFFAB47BC),
      label: 'Клуб',
      description: 'Клубная музыка',
      energy: 0.9,
      valence: 0.75,
      danceability: 0.9,
      tempo: 128,
    ),
    MoodCategory(
      name: 'romantic',
      icon: Icons.favorite,
      color: Colors.pinkAccent,
      label: 'Романтика',
      description: 'Романтическая музыка',
      energy: 0.45,
      valence: 0.85,
      danceability: 0.5,
      tempo: 90,
    ),
    MoodCategory(
      name: 'dinner',
      icon: Icons.restaurant,
      color: Color(0xFFD84315),
      label: 'Ужин',
      description: 'Фоновая музыка для ужина',
      energy: 0.35,
      valence: 0.7,
      danceability: 0.4,
      tempo: 95,
    ),

    // === РАБОТА И КОНЦЕНТРАЦИЯ ===
    MoodCategory(
      name: 'focus',
      icon: Icons.psychology,
      color: Colors.purple,
      label: 'Фокус',
      description: 'Музыка для концентрации',
      energy: 0.5,
      valence: 0.5,
      danceability: 0.3,
      tempo: 100,
    ),
    MoodCategory(
      name: 'study',
      icon: Icons.menu_book,
      color: Color(0xFF5E35B1),
      label: 'Учёба',
      description: 'Музыка для учёбы',
      energy: 0.4,
      valence: 0.55,
      danceability: 0.25,
      tempo: 95,
    ),
    MoodCategory(
      name: 'work',
      icon: Icons.work,
      color: Color(0xFF3949AB),
      label: 'Работа',
      description: 'Продуктивная музыка',
      energy: 0.55,
      valence: 0.6,
      danceability: 0.35,
      tempo: 105,
    ),
    MoodCategory(
      name: 'productive',
      icon: Icons.trending_up_outlined,
      color: Color(0xFF1E88E5),
      label: 'Продуктивность',
      description: 'Музыка для эффективности',
      energy: 0.6,
      valence: 0.65,
      danceability: 0.4,
      tempo: 110,
    ),
    MoodCategory(
      name: 'creative',
      icon: Icons.palette,
      color: Color(0xFF00897B),
      label: 'Творчество',
      description: 'Музыка для креативности',
      energy: 0.5,
      valence: 0.7,
      danceability: 0.45,
      tempo: 100,
    ),

    // === ВРЕМЕНА СУТОК ===
    MoodCategory(
      name: 'morning',
      icon: Icons.wb_sunny,
      color: Color(0xFFFDD835),
      label: 'Утро',
      description: 'Бодрая утренняя музыка',
      energy: 0.65,
      valence: 0.75,
      danceability: 0.6,
      tempo: 115,
    ),
    MoodCategory(
      name: 'afternoon',
      icon: Icons.wb_sunny_outlined,
      color: Color(0xFFFFB300),
      label: 'День',
      description: 'Дневная энергичная музыка',
      energy: 0.7,
      valence: 0.7,
      danceability: 0.65,
      tempo: 120,
    ),
    MoodCategory(
      name: 'evening',
      icon: Icons.wb_twilight,
      color: Color(0xFFFF6F00),
      label: 'Вечер',
      description: 'Расслабленная вечерняя музыка',
      energy: 0.45,
      valence: 0.6,
      danceability: 0.5,
      tempo: 95,
    ),
    MoodCategory(
      name: 'night',
      icon: Icons.nightlight,
      color: Color(0xFF283593),
      label: 'Ночь',
      description: 'Ночная атмосферная музыка',
      energy: 0.35,
      valence: 0.5,
      danceability: 0.4,
      tempo: 85,
    ),
    MoodCategory(
      name: 'late_night',
      icon: Icons.dark_mode,
      color: Color(0xFF1A237E),
      label: 'Поздняя ночь',
      description: 'Глубокая ночная музыка',
      energy: 0.3,
      valence: 0.45,
      danceability: 0.35,
      tempo: 75,
    ),

    // === АКТИВНОСТИ ===
    MoodCategory(
      name: 'driving',
      icon: Icons.directions_car,
      color: Color(0xFF43A047),
      label: 'Вождение',
      description: 'Музыка для поездок',
      energy: 0.65,
      valence: 0.7,
      danceability: 0.6,
      tempo: 110,
    ),
    MoodCategory(
      name: 'road_trip',
      icon: Icons.explore,
      color: Color(0xFF66BB6A),
      label: 'Путешествие',
      description: 'Музыка для путешествий',
      energy: 0.7,
      valence: 0.75,
      danceability: 0.65,
      tempo: 115,
    ),
    MoodCategory(
      name: 'gaming',
      icon: Icons.sports_esports,
      color: Color(0xFF7B1FA2),
      label: 'Игры',
      description: 'Музыка для гейминга',
      energy: 0.75,
      valence: 0.65,
      danceability: 0.6,
      tempo: 130,
    ),
    MoodCategory(
      name: 'cooking',
      icon: Icons.restaurant_menu,
      color: Color(0xFFE64A19),
      label: 'Готовка',
      description: 'Музыка для приготовления еды',
      energy: 0.55,
      valence: 0.7,
      danceability: 0.55,
      tempo: 105,
    ),
    MoodCategory(
      name: 'reading',
      icon: Icons.auto_stories,
      color: Color(0xFF6D4C41),
      label: 'Чтение',
      description: 'Фоновая музыка для чтения',
      energy: 0.3,
      valence: 0.6,
      danceability: 0.25,
      tempo: 80,
    ),

    // === ЖАНРОВЫЕ НАСТРОЕНИЯ ===
    MoodCategory(
      name: 'rock_energy',
      icon: Icons.music_note_outlined,
      color: Color(0xFFD32F2F),
      label: 'Рок-энергия',
      description: 'Энергичный рок',
      energy: 0.85,
      valence: 0.65,
      danceability: 0.65,
      tempo: 135,
    ),
    MoodCategory(
      name: 'pop_vibes',
      icon: Icons.star,
      color: Color(0xFFE91E63),
      label: 'Поп-вайб',
      description: 'Попсовое настроение',
      energy: 0.7,
      valence: 0.8,
      danceability: 0.75,
      tempo: 120,
    ),
    MoodCategory(
      name: 'electronic_beats',
      icon: Icons.graphic_eq,
      color: Color(0xFF00BCD4),
      label: 'Электро-биты',
      description: 'Электронные ритмы',
      energy: 0.8,
      valence: 0.7,
      danceability: 0.85,
      tempo: 128,
    ),
    MoodCategory(
      name: 'jazz_mood',
      icon: Icons.piano,
      color: Color(0xFF795548),
      label: 'Джазовое настроение',
      description: 'Джазовая атмосфера',
      energy: 0.45,
      valence: 0.65,
      danceability: 0.45,
      tempo: 95,
    ),
    MoodCategory(
      name: 'classical_elegance',
      icon: Icons.music_video,
      color: Color(0xFF607D8B),
      label: 'Классическая элегантность',
      description: 'Изысканная классика',
      energy: 0.35,
      valence: 0.7,
      danceability: 0.2,
      tempo: 90,
    ),

    // === СПЕЦИФИЧЕСКИЕ НАСТРОЕНИЯ ===
    MoodCategory(
      name: 'confidence',
      icon: Icons.emoji_events,
      color: Color(0xFFFFA000),
      label: 'Уверенность',
      description: 'Музыка для уверенности',
      energy: 0.75,
      valence: 0.7,
      danceability: 0.7,
      tempo: 115,
    ),
    MoodCategory(
      name: 'motivation',
      icon: Icons.fitness_center_outlined,
      color: Color(0xFFFF5722),
      label: 'Мотивация',
      description: 'Мотивирующая музыка',
      energy: 0.8,
      valence: 0.75,
      danceability: 0.7,
      tempo: 125,
    ),
    MoodCategory(
      name: 'anger',
      icon: Icons.warning,
      color: Color(0xFFB71C1C),
      label: 'Гнев',
      description: 'Агрессивная музыка',
      energy: 0.95,
      valence: 0.3,
      danceability: 0.6,
      tempo: 150,
    ),
    MoodCategory(
      name: 'sadness',
      icon: Icons.sentiment_very_dissatisfied,
      color: Color(0xFF37474F),
      label: 'Грусть',
      description: 'Печальная музыка',
      energy: 0.25,
      valence: 0.2,
      danceability: 0.3,
      tempo: 70,
    ),
    MoodCategory(
      name: 'dreamy',
      icon: Icons.cloud_queue,
      color: Color(0xFF9C27B0),
      label: 'Мечтательность',
      description: 'Мечтательная музыка',
      energy: 0.4,
      valence: 0.75,
      danceability: 0.4,
      tempo: 85,
    ),

    // === ИНТЕНСИВНОСТЬ ===
    MoodCategory(
      name: 'intense',
      icon: Icons.whatshot,
      color: Color(0xFFFF6F00),
      label: 'Интенсивность',
      description: 'Интенсивная музыка',
      energy: 0.9,
      valence: 0.6,
      danceability: 0.75,
      tempo: 140,
    ),
    MoodCategory(
      name: 'calm',
      icon: Icons.waves,
      color: Color(0xFF0097A7),
      label: 'Спокойствие',
      description: 'Очень спокойная музыка',
      energy: 0.25,
      valence: 0.65,
      danceability: 0.3,
      tempo: 75,
    ),
    MoodCategory(
      name: 'gentle',
      icon: Icons.eco,
      color: Color(0xFF66BB6A),
      label: 'Нежность',
      description: 'Нежная мягкая музыка',
      energy: 0.3,
      valence: 0.75,
      danceability: 0.35,
      tempo: 80,
    ),
    MoodCategory(
      name: 'aggressive',
      icon: Icons.flash_on_outlined,
      color: Color(0xFFC62828),
      label: 'Агрессия',
      description: 'Агрессивная энергичная музыка',
      energy: 0.95,
      valence: 0.4,
      danceability: 0.7,
      tempo: 160,
    ),
    MoodCategory(
      name: 'smooth',
      icon: Icons.water_drop,
      color: Color(0xFF26C6DA),
      label: 'Гладкость',
      description: 'Плавная ровная музыка',
      energy: 0.4,
      valence: 0.7,
      danceability: 0.5,
      tempo: 90,
    ),

    // === ПОГОДА И ПРИРОДА ===
    MoodCategory(
      name: 'rainy',
      icon: Icons.water,
      color: Color(0xFF546E7A),
      label: 'Дождливо',
      description: 'Музыка для дождливой погоды',
      energy: 0.35,
      valence: 0.5,
      danceability: 0.35,
      tempo: 80,
    ),
    MoodCategory(
      name: 'sunny',
      icon: Icons.wb_sunny,
      color: Color(0xFFFFC107),
      label: 'Солнечно',
      description: 'Солнечная позитивная музыка',
      energy: 0.75,
      valence: 0.85,
      danceability: 0.7,
      tempo: 120,
    ),
    MoodCategory(
      name: 'stormy',
      icon: Icons.thunderstorm,
      color: Color(0xFF455A64),
      label: 'Гроза',
      description: 'Драматичная бурная музыка',
      energy: 0.7,
      valence: 0.4,
      danceability: 0.5,
      tempo: 110,
    ),
    MoodCategory(
      name: 'winter',
      icon: Icons.ac_unit,
      color: Color(0xFF81D4FA),
      label: 'Зима',
      description: 'Холодная зимняя музыка',
      energy: 0.4,
      valence: 0.6,
      danceability: 0.4,
      tempo: 85,
    ),
    MoodCategory(
      name: 'summer',
      icon: Icons.beach_access,
      color: Color(0xFFFFD54F),
      label: 'Лето',
      description: 'Лётняя жаркая музыка',
      energy: 0.7,
      valence: 0.85,
      danceability: 0.75,
      tempo: 118,
    ),

    // === ДОПОЛНИТЕЛЬНЫЕ 50+ КАТЕГОРИЙ ===
    MoodCategory(
      name: 'acoustic',
      icon: Icons.music_note,
      color: Color(0xFF8D6E63),
      label: 'Акустика',
      description: 'Акустическая музыка',
      energy: 0.4,
      valence: 0.65,
      danceability: 0.4,
      tempo: 95,
    ),
    MoodCategory(
      name: 'epic',
      icon: Icons.landscape,
      color: Color(0xFF424242),
      label: 'Эпично',
      description: 'Эпическая музыка',
      energy: 0.75,
      valence: 0.6,
      danceability: 0.45,
      tempo: 120,
    ),
    MoodCategory(
      name: 'cinematic',
      icon: Icons.movie,
      color: Color(0xFF5D4037),
      label: 'Кинематограф',
      description: 'Кинематографичная музыка',
      energy: 0.55,
      valence: 0.6,
      danceability: 0.3,
      tempo: 100,
    ),
    MoodCategory(
      name: 'experimental',
      icon: Icons.science,
      color: Color(0xFF00897B),
      label: 'Экспериментальная',
      description: 'Экспериментальные звуки',
      energy: 0.5,
      valence: 0.5,
      danceability: 0.4,
      tempo: 95,
    ),
    MoodCategory(
      name: 'retro',
      icon: Icons.radio,
      color: Color(0xFFFF7043),
      label: 'Ретро',
      description: 'Ретро музыка',
      energy: 0.6,
      valence: 0.7,
      danceability: 0.65,
      tempo: 110,
    ),
    MoodCategory(
      name: 'vintage',
      icon: Icons.history_edu,
      color: Color(0xFFA1887F),
      label: 'Винтаж',
      description: 'Винтажная музыка',
      energy: 0.45,
      valence: 0.65,
      danceability: 0.5,
      tempo: 95,
    ),
    MoodCategory(
      name: 'futuristic',
      icon: Icons.rocket_launch,
      color: Color(0xFF00BCD4),
      label: 'Футуристичная',
      description: 'Футуристичная музыка',
      energy: 0.7,
      valence: 0.65,
      danceability: 0.75,
      tempo: 125,
    ),
    MoodCategory(
      name: 'mysterious',
      icon: Icons.psychology_alt,
      color: Color(0xFF4A148C),
      label: 'Загадочная',
      description: 'Таинственная музыка',
      energy: 0.45,
      valence: 0.45,
      danceability: 0.4,
      tempo: 85,
    ),
    MoodCategory(
      name: 'dark',
      icon: Icons.dark_mode_outlined,
      color: Color(0xFF212121),
      label: 'Тёмная',
      description: 'Тёмная атмосферная музыка',
      energy: 0.55,
      valence: 0.3,
      danceability: 0.5,
      tempo: 100,
    ),
    MoodCategory(
      name: 'bright',
      icon: Icons.light_mode,
      color: Color(0xFFFFEB3B),
      label: 'Яркая',
      description: 'Яркая позитивная музыка',
      energy: 0.8,
      valence: 0.9,
      danceability: 0.75,
      tempo: 125,
    ),
    MoodCategory(
      name: 'groovy',
      icon: Icons.graphic_eq_outlined,
      color: Color(0xFFFF6F00),
      label: 'Грувовая',
      description: 'Грувовая ритмичная музыка',
      energy: 0.7,
      valence: 0.75,
      danceability: 0.85,
      tempo: 115,
    ),
    MoodCategory(
      name: 'funky',
      icon: Icons.celebration_outlined,
      color: Color(0xFFE040FB),
      label: 'Фанковая',
      description: 'Фанк музыка',
      energy: 0.75,
      valence: 0.8,
      danceability: 0.9,
      tempo: 120,
    ),
    MoodCategory(
      name: 'soulful',
      icon: Icons.favorite_border,
      color: Color(0xFF6A1B9A),
      label: 'Душевная',
      description: 'Душевная музыка',
      energy: 0.5,
      valence: 0.7,
      danceability: 0.55,
      tempo: 95,
    ),
    MoodCategory(
      name: 'bluesy',
      icon: Icons.music_note_outlined,
      color: Color(0xFF1565C0),
      label: 'Блюзовая',
      description: 'Блюзовая музыка',
      energy: 0.5,
      valence: 0.5,
      danceability: 0.45,
      tempo: 85,
    ),
    MoodCategory(
      name: 'indie',
      icon: Icons.album,
      color: Color(0xFF00796B),
      label: 'Инди',
      description: 'Инди музыка',
      energy: 0.6,
      valence: 0.65,
      danceability: 0.6,
      tempo: 105,
    ),
    MoodCategory(
      name: 'alternative',
      icon: Icons.alt_route,
      color: Color(0xFF689F38),
      label: 'Альтернатива',
      description: 'Альтернативная музыка',
      energy: 0.65,
      valence: 0.6,
      danceability: 0.6,
      tempo: 110,
    ),
    MoodCategory(
      name: 'punk',
      icon: Icons.flash_on_outlined,
      color: Color(0xFFD32F2F),
      label: 'Панк',
      description: 'Панк-рок музыка',
      energy: 0.9,
      valence: 0.65,
      danceability: 0.7,
      tempo: 145,
    ),
    MoodCategory(
      name: 'metal',
      icon: Icons.whatshot_outlined,
      color: Color(0xFF212121),
      label: 'Металл',
      description: 'Тяжёлая металл музыка',
      energy: 0.95,
      valence: 0.45,
      danceability: 0.6,
      tempo: 150,
    ),
    MoodCategory(
      name: 'reggae',
      icon: Icons.beach_access_outlined,
      color: Color(0xFF4CAF50),
      label: 'Регги',
      description: 'Регги музыка',
      energy: 0.55,
      valence: 0.75,
      danceability: 0.7,
      tempo: 95,
    ),
    MoodCategory(
      name: 'latin',
      icon: Icons.music_note,
      color: Color(0xFFE91E63),
      label: 'Латина',
      description: 'Латинская музыка',
      energy: 0.8,
      valence: 0.85,
      danceability: 0.9,
      tempo: 120,
    ),
    MoodCategory(
      name: 'salsa',
      icon: Icons.music_note,
      color: Color(0xFFFF5722),
      label: 'Сальса',
      description: 'Сальса танцы',
      energy: 0.85,
      valence: 0.9,
      danceability: 0.95,
      tempo: 125,
    ),
    MoodCategory(
      name: 'tango',
      icon: Icons.favorite_outline,
      color: Color(0xFF880E4F),
      label: 'Танго',
      description: 'Страстное танго',
      energy: 0.6,
      valence: 0.65,
      danceability: 0.75,
      tempo: 100,
    ),
    MoodCategory(
      name: 'bossa_nova',
      icon: Icons.beach_access,
      color: Color(0xFF26A69A),
      label: 'Босса-нова',
      description: 'Босса-нова ритмы',
      energy: 0.45,
      valence: 0.75,
      danceability: 0.6,
      tempo: 95,
    ),
    MoodCategory(
      name: 'swing',
      icon: Icons.music_note_outlined,
      color: Color(0xFFBF360C),
      label: 'Свинг',
      description: 'Свинг джаз',
      energy: 0.65,
      valence: 0.8,
      danceability: 0.75,
      tempo: 140,
    ),
    MoodCategory(
      name: 'blues',
      icon: Icons.sentiment_neutral,
      color: Color(0xFF1A237E),
      label: 'Блюз',
      description: 'Классический блюз',
      energy: 0.45,
      valence: 0.45,
      danceability: 0.4,
      tempo: 80,
    ),
    MoodCategory(
      name: 'country',
      icon: Icons.agriculture,
      color: Color(0xFF6D4C41),
      label: 'Кантри',
      description: 'Кантри музыка',
      energy: 0.6,
      valence: 0.7,
      danceability: 0.65,
      tempo: 110,
    ),
    MoodCategory(
      name: 'folk',
      icon: Icons.nature_people,
      color: Color(0xFF558B2F),
      label: 'Фолк',
      description: 'Народная музыка',
      energy: 0.5,
      valence: 0.65,
      danceability: 0.5,
      tempo: 95,
    ),
    MoodCategory(
      name: 'gospel',
      icon: Icons.church,
      color: Color(0xFF4A148C),
      label: 'Госпел',
      description: 'Духовная госпел музыка',
      energy: 0.7,
      valence: 0.8,
      danceability: 0.6,
      tempo: 110,
    ),
    MoodCategory(
      name: 'opera',
      icon: Icons.theater_comedy,
      color: Color(0xFF880E4F),
      label: 'Опера',
      description: 'Оперная музыка',
      energy: 0.6,
      valence: 0.65,
      danceability: 0.2,
      tempo: 90,
    ),
    MoodCategory(
      name: 'orchestra',
      icon: Icons.piano_outlined,
      color: Color(0xFF4E342E),
      label: 'Оркестр',
      description: 'Оркестровая музыка',
      energy: 0.55,
      valence: 0.7,
      danceability: 0.25,
      tempo: 95,
    ),
    MoodCategory(
      name: 'symphony',
      icon: Icons.music_video_outlined,
      color: Color(0xFF37474F),
      label: 'Симфония',
      description: 'Симфоническая музыка',
      energy: 0.5,
      valence: 0.7,
      danceability: 0.2,
      tempo: 90,
    ),
    MoodCategory(
      name: 'lofi',
      icon: Icons.headphones,
      color: Color(0xFF9575CD),
      label: 'Lo-Fi',
      description: 'Lo-Fi hip-hop beats',
      energy: 0.35,
      valence: 0.6,
      danceability: 0.5,
      tempo: 85,
    ),
    MoodCategory(
      name: 'trap',
      icon: Icons.music_note,
      color: Color(0xFF6A1B9A),
      label: 'Трэп',
      description: 'Трэп музыка',
      energy: 0.8,
      valence: 0.6,
      danceability: 0.8,
      tempo: 140,
    ),
    MoodCategory(
      name: 'drill',
      icon: Icons.speaker,
      color: Color(0xFF212121),
      label: 'Дрилл',
      description: 'Дрилл музыка',
      energy: 0.85,
      valence: 0.5,
      danceability: 0.75,
      tempo: 145,
    ),
    MoodCategory(
      name: 'afrobeat',
      icon: Icons.celebration,
      color: Color(0xFFFF6F00),
      label: 'Афробит',
      description: 'Афробит ритмы',
      energy: 0.8,
      valence: 0.85,
      danceability: 0.9,
      tempo: 115,
    ),
    MoodCategory(
      name: 'kpop',
      icon: Icons.star_outlined,
      color: Color(0xFFE91E63),
      label: 'K-Pop',
      description: 'Корейская поп-музыка',
      energy: 0.85,
      valence: 0.85,
      danceability: 0.9,
      tempo: 130,
    ),
    MoodCategory(
      name: 'jpop',
      icon: Icons.star_half,
      color: Color(0xFFEC407A),
      label: 'J-Pop',
      description: 'Японская поп-музыка',
      energy: 0.8,
      valence: 0.85,
      danceability: 0.85,
      tempo: 125,
    ),
  ];

  // Получить категорию по имени
  static MoodCategory? getByName(String name) {
    try {
      return all.firstWhere((category) => category.name == name);
    } catch (e) {
      return null;
    }
  }

  // Получить случайные категории
  static List<MoodCategory> getRandom(int count) {
    final shuffled = List<MoodCategory>.from(all)..shuffle();
    return shuffled.take(count).toList();
  }

  // Фильтровать по энергии
  static List<MoodCategory> filterByEnergy(double minEnergy, double maxEnergy) {
    return all.where((c) => c.energy >= minEnergy && c.energy <= maxEnergy).toList();
  }

  // Фильтровать по настроению (valence)
  static List<MoodCategory> filterByValence(double minValence, double maxValence) {
    return all.where((c) => c.valence >= minValence && c.valence <= maxValence).toList();
  }
}
