// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ABkak4m3y2rcS-queAGFVd8acHQSLr4',
    appId: '1:972658834954:web:950bb8c4c41140df07a9f3',
    messagingSenderId: '972658834954',
    projectId: 'aimusic-8a2d1',
    authDomain: 'aimusic-8a2d1.firebaseapp.com',
    storageBucket: 'aimusic-8a2d1.firebasestorage.app',
    measurementId: 'G-QS2ZQ134JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWHgigMiylxSjLmb-CrdZPQpEaiuksqgE',
    appId: '1:972658834954:android:c92e854fc05cf1bb07a9f3',
    messagingSenderId: '972658834954',
    projectId: 'aimusic-8a2d1',
    storageBucket: 'aimusic-8a2d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9IaG6hP5xnkvLBe_z99TUEWZRBAbF1d4',
    appId: '1:972658834954:ios:d43343c9c729470b07a9f3',
    messagingSenderId: '972658834954',
    projectId: 'aimusic-8a2d1',
    storageBucket: 'aimusic-8a2d1.firebasestorage.app',
    iosBundleId: 'com.example.vibe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4ABkak4m3y2rcS-queAGFVd8acHQSLr4',
    appId: '1:972658834954:web:573991fa2612ce9007a9f3',
    messagingSenderId: '972658834954',
    projectId: 'aimusic-8a2d1',
    authDomain: 'aimusic-8a2d1.firebaseapp.com',
    storageBucket: 'aimusic-8a2d1.firebasestorage.app',
    measurementId: 'G-VZZCKM0SSV',
  );
}
